### ISSUE TITLE
Backslash is printed in MARC file if the indicator is a space

### ISSUE THREAD

**Issue by Terrychung** [edsu/pymarc#102]
I have discovered that if the field object detect the indicator is a space, it will be converted as '\\\\' 

> 
            for indicator in self.indicators:
                if indicator in (' ','\\'):
                    text += '\\'
                else:
                    text += '%s' % indicator

The "\\" will be printed in the MARC file, another library such as Perl's MARC::Record will trigger it as an invalid indicator.

**Comment by edsu** [comment]
[This](https://github.com/edsu/pymarc/blob/master/pymarc/field.py#L72-L76) logic is only relevant for the MARCMaker format, or when you print a record as a string. Is this what you are doing? MARCMaker/Breaker [says, or really shows] that you need to use a backslash instead of a space.
