### ISSUE TITLE
New release to PyPI to make Python 3 support official?

### ISSUE THREAD

**Issue by cclauss** [edsu/pymarc#127]
https://github.com/edsu/pymarc/blob/master/setup.py#L24 should cause PyPI to register that both Python 2 and Python 3 are supported.

**Comment by Wooble** [comment]
I've added python_requires in #128 (and removed some useless pre-2.6 conditional deps) which might be nice to have before a new release.

**Comment by edsu** [comment]
.Merged and released as [v3.1.11](https://pypi.org/project/pymarc/) thanks for your help as always.
