### ISSUE TITLE
Corrupt / Incompatible data: couldn't find 0x20 in g0=83 g1=69

### ISSUE THREAD

**Issue by Kerang** [edsu/pymarc#129]
I was getting the error: couldn't find 0x20 in g0=83 g1=69

That error eventually, led me down the right path, to the fact that the data was corrupt / was in the wrong encoding type. It should have shown Pi Squared, but instead it showed some weird characters.

An error that says something about unable to parse characters would have been helpful. I get that may be what it's saying, just in a more esoteric form, but it would be nice if it said something more like:
Unable to parse character 0x20 in g0=83 g1=69.

**Comment by edsu** [comment]
Great idea, thanks for the suggestion. These things matter.
