### ISSUE TITLE
Add subfields at an arbitrary position

### ISSUE THREAD

**Issue by Wooble** [edsu/pymarc#130]
from the mailing list:

> But maybe it would be useful if the Field.add_subfield method took an optional 0 based position that defaults to the end of the field to preserve existing behavior? For example:
> 
>     field = record.title()
>     field.add_subfield('a', 'Middlemarch :', pos=0)

This shouldn't be difficult to implement, and seems a lot nicer than manipulating the internal heterogeneous list of code, data, code, data manually.

**Comment by souzaluuk** [comment]
Are you still interested in this?
I can do?

**Comment by Wooble** [comment]
I don't even remember why I wanted this anymore, but thanks! :)
