### ISSUE TITLE
Document use of MARCXML with an example

### ISSUE THREAD

**Issue by nichtich** [edsu/pymarc#134]
We are still trying to find out how to parse and serialize MARCXML. I then stumbled upon #73 (make it simpler) but one or two examples in the documentation may be enough to start with:

* how to read a full MARCXML file
* how to read a stream of records from  a MARCXML file (maybe [this helps](https://github.com/scriptotek/mc2skos/blob/master/mc2skos/reader.py))
* how to serialize MARC records to XML

P.S: See also [this help request](https://groups.google.com/forum/#!topic/pymarc/PRe3LZEXQZo).

**Comment by edsu** [comment]
Sure, I'd be happy to merge those. Although the referenced ticket, which I've intentionally left open, makes it sound like there could be a preferable API for reading/writing XML?

**Comment by edsu** [comment]
@nichtich do you know if [lxml.etree.iterparse](https://lxml.de/api/lxml.etree.iterparse-class.html) reads the entire document into memory, and then iterates over that?

**Comment by edsu** [comment]
@nichtich Will this [new documentation](https://github.com/edsu/pymarc#json-and-xml) help clarify the current state of affairs with XML and JSON? It can always get updated if there does turn out to be progress on #73. If you have any suggestions for improving it please send them along.

**Comment by nichtich** [comment]
@edsu Thanks for the new documentation that's very helpful, I did not know about `map_xml`. Writing XML is possible nevertheless. The following is possibly no beautiful Python but should work:

~~~python
# write XML header to file object
file.write('<?xml version="1.0" encoding="UTF-8"?>\n')
file.write('<collection xmlns="http://www.loc.gov/MARC21/slim">\n')

# write records
for record in records:
     file.write(marcxml.record_to_xml(record).decode("utf-8"))
     file.write('\n')

# write XML footer
file.write('</collection>')
file.close()
~~~

**Comment by edsu** [comment]
That would be better expressed in a separate pull request. If the documentation suffices for now I'm going to close this.
