### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jayvdb** [edsu/pymarc#140]
setup.py says "BSD License" but I can not find anything more precise that this.

Which license is this repository?  Could you create a LICENSE file so that tools can automatically detect the license.

**Comment by Wooble** [comment]
It does link to https://opensource.org/licenses/bsd-license.php which is explicitly the 2-clause BSD license but I agree it's probably a good idea to have a LICENSE file in the repo itself.

**Comment by jayvdb** [comment]
Thanks.  I am packaging this at https://build.opensuse.org/package/show/home:jayvdb:py-new/python-pymarc , and it is otherwise good, but I know the maintainers will complain about the license.

**Comment by edsu** [comment]
I'd be open to changing it to another open source license if it makes it easier to package up. I'll add the LICENSE file to make things more explicit.

**Comment by jayvdb** [comment]
It can be any OSI license, as long as it isnt ambiguous.  And the LICENSE file is the critical bit, because packaging tools put that file in a different directory than the README.  In rpm .spec files, there is a %doc macro and a %license macro, and in openSUSE the policy is now that both are required.

**Comment by edsu** [comment]
Does this need to be on PyPI or will GitHub suffice for now?

**Comment by jayvdb** [comment]
GitHub is fine.  Thanks so much.

**Comment by edsu** [comment]
@jayvdb Thank you!

**Comment by jayvdb** [comment]
Submitted for inclusion into openSUSE main repos https://build.opensuse.org/request/show/720333
