### ISSUE TITLE
readthedocs

### ISSUE THREAD

**Issue by edsu** [edsu/pymarc#38]
It would be nice to get pymarc up on readthedocs.

**Comment by Wooble** [comment]
There is a pymarc on readthedocs, but it's from a fork that's way behind this repo. I don't know if it's even possible to reclaim the URL on RTD, but reaching out to the maintainer might be worthwhile?

**Comment by edsu** [comment]
I think @kayiwa holds the keys to RTD?

**Comment by kayiwa** [comment]
I deleted it. I haven't the bandwidth for that. I'll be happy to contribute however.

**Comment by Wooble** [comment]
FWIW, https://readthedocs.org/projects/pymarc/ still says you own it.

**Comment by edsu** [comment]
@kayiwa any chance you can help resolve this?

**Comment by kayiwa** [comment]
I swear I deleted it last time. I've done so again.

**Comment by edsu** [comment]
I'm not sure this matters much anymore.

**Comment by Wooble** [comment]
The name does seem to be available on readthedocs now... I know I'd find it helpful to have generated API documentation online; I find myself reading the source to find a lot of stuff. 

I'd be happy to work on the autodoc configuration and send a PR, but I don't want to register the project on readthedocs myself...

**Comment by edsu** [comment]
@wooble that would be awesome! why don't you want to register it?

**Comment by Wooble** [comment]
Mostly because I think the way rtfd works would require it to use my fork, and then if it's not kept up to date with yours the docs won't match what is actually released. Like before. :)

**Comment by edsu** [comment]
This reminds me I've been meaning to ask you if you want to help maintain pymarc as a collaborator on the repository. You have contributed so much to the code and the community side I was wondering if you would be willing.

**Comment by Wooble** [comment]
That works; thanks. I was able to register the rtfd project to point to this repo now; it just needs the webhook activated.

(Also, the docstrings could use some cleanup; the generated docs aren't all that pretty but they beat opening the source to find things anyway)

**Comment by edsu** [comment]
Yeah, having them public will be a good incentive to clean them up. I'll look into the webhook.

**Comment by edsu** [comment]
I think I just activated the webhook ...

**Comment by edsu** [comment]
Ok, it looks like it's working :-) now we need better docs, heh.
