### ISSUE TITLE
Extend Writer with JSONWriter, XMLWriter and TextWriter

### ISSUE THREAD

**Issue by jimnicholls** [edsu/pymarc#76]
The only subclass of Writer we have is MARCWriter.

I would like to create a few more subclasses of Writer.
* JSONWriter that outputs an array of MARC-in-JSON objects.
* XMLWriter that outputs a MARCXML collection.
* TextWriter that outputs str(record), with a blank link between records.

My motivation here is so I can code to the generic Writer interface and plug in different writers as need be. Particularly I want to plug in a TextWriter during development, but a MARCWriter in production.

**Comment by edsu** [comment]
Ok, that sounds cool :-)

**Comment by edsu** [comment]
Just released as v3.1.4! Thanks for your work! :cake:
