### ISSUE TITLE
Creating a Record with a particular leader

### ISSUE THREAD

**Issue by jimnicholls** [edsu/pymarc#77]
I'm exporting records from our library system and I need to replicate the leader field where it makes sense to do so. Record's API does not allow me to do that.

Can I propose the addition of a leader keyword argument to __init__ of Record? This argument would default to `' ' * LEADER_LEN`.

Leader positions 5 through 8 and 17 through 19 would be taken from the leader argument. The other leader positions would be set or calculated, as is currently done.

Happy to submit a pull request if this proposal is acceptable.

**Comment by edsu** [comment]
:+1:
